#!/bin/bash
# write_sandbox.sh — Generate SandboxVars.lua from PZ_SBX_* environment variables
#
# PZ expects a specific Lua format. Numeric values are unquoted; strings are quoted.
# The EnabledMods field mirrors the Mods= list from the ini file.
set -euo pipefail

SERVER_NAME="${SERVER_NAME:-zomboid}"
SANDBOX_FILE="/data/Server/${SERVER_NAME}_SandboxVars.lua"
RESOLVED_MODS="${RESOLVED_MODS:-}"

log() { echo "[write_sandbox] $*"; }

log "Writing ${SANDBOX_FILE}..."

# Determine if a value should be quoted (non-numeric = string)
is_numeric() {
    [[ "$1" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]
}

{
    echo "-- Generated by Docker entrypoint — $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "-- Edit .env and restart the container to change settings"
    echo "VERSION = 1,"
    echo "SandboxVars = {"

    # Write all PZ_SBX_* vars (skip EnabledMods — handled explicitly below)
    while IFS='=' read -r VARNAME VALUE; do
        KEY="${VARNAME#PZ_SBX_}"
        [ "$KEY" = "EnabledMods" ] && continue

        if is_numeric "$VALUE"; then
            printf ' %s = %s,\n' "$KEY" "$VALUE"
        else
            printf ' %s = "%s",\n' "$KEY" "$VALUE"
        fi
    done < <(env | grep '^PZ_SBX_' | sort)

    # EnabledMods uses the same semicolon-separated mod ID list as Mods= in the ini
    ENABLED_MODS="${RESOLVED_MODS:-${PZ_INI_Mods:-}}"
    printf ' EnabledMods = "%s",\n' "$ENABLED_MODS"

    echo "}"

} > "${SANDBOX_FILE}"

log "Done — ${SANDBOX_FILE}"
