#!/bin/bash
# write_ini.sh — Generate the PZ server .ini from PZ_INI_* environment variables
#
# All PZ_INI_Key=Value env vars map directly to Key=Value in the ini file.
# RESOLVED_MODS and RESOLVED_WORKSHOP (set by entrypoint.sh) override Mods/WorkshopItems.
set -euo pipefail

SERVER_NAME="${SERVER_NAME:-zomboid}"
RCON_PORT="${RCON_PORT:-27015}"
SERVER_PORT="${SERVER_PORT:-16261}"
INI_FILE="/data/Server/${SERVER_NAME}.ini"

log() { echo "[write_ini] $*"; }

log "Writing ${INI_FILE}..."

# ── Build ini content ─────────────────────────────────────────────────────────
{
    echo "# Generated by Docker entrypoint — $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Edit .env and restart the container to change settings"
    echo ""

    # Write all PZ_INI_* vars, skipping Mods and WorkshopItems (handled below)
    # Read the full line and strip only the PZ_INI_ prefix, preserving any '=' in the value
    while IFS= read -r LINE; do
        KEY="${LINE#PZ_INI_}"   # strip prefix; KEY is now "PublicName=My Server" etc.

        INI_KEY="${KEY%%=*}"    # everything before the first '='
        INI_VAL="${KEY#*=}"     # everything after the first '='

        # Skip mod lists — we handle them separately with resolved values
        [ "$INI_KEY" = "Mods" ] && continue
        [ "$INI_KEY" = "WorkshopItems" ] && continue

        echo "${INI_KEY}=${INI_VAL}"
    done < <(env | grep '^PZ_INI_' | sort)

    # ── Mod lists: prefer resolved (from collection) over manual env vars ──────
    MANUAL_MODS="${PZ_INI_Mods:-}"
    MANUAL_WORKSHOP="${PZ_INI_WorkshopItems:-}"
    RESOLVED_MODS="${RESOLVED_MODS:-}"
    RESOLVED_WORKSHOP="${RESOLVED_WORKSHOP:-}"

    # Merge: resolved values take precedence; manual values appended as fallback
    # if there's no overlap (supports pure-manual config when no collection is set)
    if [ -n "${RESOLVED_MODS}" ]; then
        FINAL_MODS="${RESOLVED_MODS}"
        [ -n "${MANUAL_MODS}" ] && FINAL_MODS="${FINAL_MODS};${MANUAL_MODS}"
    else
        FINAL_MODS="${MANUAL_MODS}"
    fi

    if [ -n "${RESOLVED_WORKSHOP}" ]; then
        FINAL_WORKSHOP="${RESOLVED_WORKSHOP}"
        [ -n "${MANUAL_WORKSHOP}" ] && FINAL_WORKSHOP="${FINAL_WORKSHOP};${MANUAL_WORKSHOP}"
    else
        FINAL_WORKSHOP="${MANUAL_WORKSHOP}"
    fi

    echo "Mods=${FINAL_MODS}"
    echo "WorkshopItems=${FINAL_WORKSHOP}"

    # Always write the network ports from env (these also live in ini)
    echo "DefaultPort=${SERVER_PORT}"
    echo "RCONPort=${RCON_PORT}"

} > "${INI_FILE}"

log "Done — $(wc -l < "${INI_FILE}") lines written"
